### ISSUE TITLE
Odd error message when exiting interactive python session

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/gcr-catalogs#199]
Sometimes, when I exit an interactive python session in which I have imported a catalog (specifically, `cosmoDC2_v1.0_image_addon_knots`), I get the following message upon running `exit()`

```
Exception ignored in: <generator object CosmoDC2ParentClass._iter_native_dataset at 0x2ac30214eaf0>
Traceback (most recent call last):
  File "/global/homes/d/danielsf/gcr-catalogs-desc/GCRCatalogs/cosmodc2.py", line 289, in _iter_native_dataset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2804)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/h5py/_hl/files.py", line 317, in __exit__
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/h5py/_hl/files.py", line 288, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 236, in h5py.h5f.get_obj_ids (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/h5f.c:3474)
  File "h5py/h5i.pyx", line 37, in h5py.h5i.wrap_identifier (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/h5i.c:1146)
```

**Comment by yymao** [comment]
@danielsf does this happen when you exit the session while something is still running on the catalog, or does it also happen when you exit while the session is idle?

**Comment by danielsf** [comment]
Here you go
```
danielsf@cori12:~> source setup_cosmoDC2_env.sh 
Now setup any necessary stack packages such as: setup lsst_distrib or lsst_sims
danielsf@cori12:~> python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import GCRCatalogs
>>> cat=GCRCatalogs.load_catalog('cosmoDC2_v1.0_image_addon_knots')
/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/GCR/composite.py:110: UserWarning: CompositeCatalog is still an experimental feature. Use with care!
  warnings.warn('CompositeCatalog is still an experimental feature. Use with care!')
>>> qties = cat.get_quantities(['stellar_mass_bulge', 'A_v_bulge'])
>>> import numpy as np
>>> offenders = np.where(np.logical_and(qties['stellar_mass_bulge']>0.0,
... np.logical_not(np.isfinite(qties['A_v_bulge']))))
>>> offenders
(array([], dtype=int64),)
>>> exit()
Exception ignored in: <generator object CosmoDC2ParentClass._iter_native_dataset at 0x2b5b66805af0>
Traceback (most recent call last):
  File "/global/homes/d/danielsf/gcr-catalogs-desc/GCRCatalogs/cosmodc2.py", line 289, in _iter_native_dataset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2804)
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/h5py/_hl/files.py", line 317, in __exit__
  File "/global/common/software/lsst/common/miniconda/py3-4.3.21-env/lib/python3.6/site-packages/h5py/_hl/files.py", line 288, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 236, in h5py.h5f.get_obj_ids (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/h5f.c:3474)
  File "h5py/h5i.pyx", line 37, in h5py.h5i.wrap_identifier (/home/ilan/minonda/conda-bld/h5py_1496889914775/work/h5py/h5i.c:1146)
SystemError: Parent module 'h5py' not loaded, cannot perform relative import
```

**Comment by danielsf** [comment]
That setup command sets up a clone of gcr-catalogs, so it's possible that I'm out of date....

**Comment by yymao** [comment]
@danielsf, thanks. Seems to be a Python/h5py issue but I haven't been able to track down the origin. I can reproduce the error with python but not with ipython.

**Comment by yymao** [comment]
I am closing this since this issue is most likely due to upstream packages and I haven't heard further complaints from users.
